version: '2'
services:
  ql_web:
    image: whyour/qinglong:2.17.9
    container_name: ql
    volumes:
      - ./qinglong/data:/ql/data
      - ./qinglong/deps/pnpm:/root/.local/share/pnpm
      - ./qinglong/deps/pip3:/usr/local/lib/python3.11/site-packages
    ports:
      - "5700:5700"
    restart: unless-stopped
